added check for syncing authors which do not already exist in wordpress.
passle/passle-sync-wordpress pull request #55
Opened 2024-04-19 12:55 UTC by oscar-welton

2024-04-23 10:59 UTC, passle-chris commented on class/SyncHandlers/SyncHandlerBase.php
> +    // check if any knew authors need syncing.
Wrong (k)new...

2024-04-29 09:37 UTC, klikas requested changes

2024-04-29 09:37 UTC, klikas commented on class/SyncHandlers/SyncHandlerBase.php
> +        $author_post = wp_filter_object_list($author_profiles, array('post_name' => $all_author_shortcodes_on_post));
Is this variable meant to mean "$author_exists_in_wp"? A better name here may be useful

2024-04-29 09:52 UTC, klikas approved these changes

2024-04-29 09:53 UTC, merged